version: '3'
services:

    hadoop001:
        image: registry.cn-beijing.aliyuncs.com/dreamhunter/hadoop-docker:1.0
        container_name: hadoop001
        hostname: hadoop001
        command: sh /opt/start.sh
        depends_on:
            - hadoop002
            - hadoop003
        volumes:
            # hadoop-bin 存放 release 文件
            - ../hadoop-bin:/opt/hadoop
            - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
            - ./conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
            - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
            - ./conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
            - ./conf/workers:/opt/hadoop/etc/hadoop/workers
            - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
            - ./data/hadoop001data:/opt/hadoopdata
            - ./start.sh:/opt/start.sh
        ports:
            - 9870:9870
            - 8088:8088
            - 8020:8020
            - 9866:9866

    hadoop002:
        image: registry.cn-beijing.aliyuncs.com/dreamhunter/hadoop-docker:1.0
        container_name: hadoop002
        hostname: hadoop002
        command: sh /opt/start_slave.sh
        volumes:
            - ../hadoop-bin:/opt/hadoop
            - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
            - ./conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
            - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
            - ./conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
            - ./conf/workers:/opt/hadoop/etc/hadoop/workers
            - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
            - ./data/hadoop002data:/opt/hadoopdata
            - ./start_slave.sh:/opt/start_slave.sh

    hadoop003:
        image: registry.cn-beijing.aliyuncs.com/dreamhunter/hadoop-docker:1.0
        container_name: hadoop003
        hostname: hadoop003
        command: sh /opt/start_slave.sh
        volumes:
            - ../hadoop-bin:/opt/hadoop
            - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
            - ./conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
            - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
            - ./conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
            - ./conf/workers:/opt/hadoop/etc/hadoop/workers
            - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
            - ./data/hadoop003data:/opt/hadoopdata
            - ./start_slave.sh:/opt/start_slave.sh
