version: '3'
services:

    hadoop001:
        image: hadoop:1.0
        container_name: hadoop001
        hostname: hadoop001
        command: sh /opt/start.sh
        depends_on:
            - hadoop002
            - hadoop003
        volumes:
            - ./ssh/authorized_keys:/root/.ssh/authorized_keys
            - ./ssh/id_rsa:/root/.ssh/id_rsa
            - ./ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
            - ./hadoop:/opt/hadoop
            - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
            - ./conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
            - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
            - ./conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
            - ./conf/workers:/opt/hadoop/etc/hadoop/workers
            - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
            - ./sbin/start-dfs.sh:/opt/hadoop/sbin/start-dfs.sh
            - ./sbin/start-yarn.sh:/opt/hadoop/sbin/start-yarn.sh
            - ./sbin/stop-dfs.sh:/opt/hadoop/sbin/stop-dfs.sh
            - ./sbin/stop-yarn.sh:/opt/hadoop/sbin/stop-yarn.sh
            - ./data/hadoop001data:/opt/hadoopdata
            - ./start.sh:/opt/start.sh
        ports:
            - 9870:9870
            - 8088:8088
            - 8020:8020
            - 9866:9866

    hadoop002:
        image: hadoop:1.0
        container_name: hadoop002
        hostname: hadoop002
        build:
            context: .
            dockerfile: Dockerfile
        command: sh /opt/start_slave.sh
        volumes:
            - ./ssh/authorized_keys:/root/.ssh/authorized_keys
            - ./ssh/id_rsa:/root/.ssh/id_rsa
            - ./ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
            - ./hadoop:/opt/hadoop
            - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
            - ./conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
            - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
            - ./conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
            - ./conf/workers:/opt/hadoop/etc/hadoop/workers
            - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
            - ./sbin/start-dfs.sh:/opt/hadoop/sbin/start-dfs.sh
            - ./sbin/start-yarn.sh:/opt/hadoop/sbin/start-yarn.sh
            - ./sbin/stop-dfs.sh:/opt/hadoop/sbin/stop-dfs.sh
            - ./sbin/stop-yarn.sh:/opt/hadoop/sbin/stop-yarn.sh
            - ./data/hadoop002data:/opt/hadoopdata
            - ./start_slave.sh:/opt/start_slave.sh

    hadoop003:
        image: hadoop:1.0
        container_name: hadoop003
        hostname: hadoop003
        command: sh /opt/start_slave.sh
        volumes:
            - ./ssh/authorized_keys:/root/.ssh/authorized_keys
            - ./ssh/id_rsa:/root/.ssh/id_rsa
            - ./ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
            - ./hadoop:/opt/hadoop
            - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
            - ./conf/hadoop-env.sh:/opt/hadoop/etc/hadoop/hadoop-env.sh
            - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
            - ./conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
            - ./conf/workers:/opt/hadoop/etc/hadoop/workers
            - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
            - ./sbin/start-dfs.sh:/opt/hadoop/sbin/start-dfs.sh
            - ./sbin/start-yarn.sh:/opt/hadoop/sbin/start-yarn.sh
            - ./sbin/stop-dfs.sh:/opt/hadoop/sbin/stop-dfs.sh
            - ./sbin/stop-yarn.sh:/opt/hadoop/sbin/stop-yarn.sh
            - ./data/hadoop003data:/opt/hadoopdata
            - ./start_slave.sh:/opt/start_slave.sh
